[package]
name = "section_testing"
version = "0.0.5"
description = "A library for section-style testing"
license = "MIT"
authors = ["Evan Wallace"]
readme = "README.md"
repository = "https://github.com/evanw/section_testing"
